version: "3.9"
services:
  php:
    build:
      context: .
      dockerfile: ../dockerfiles/php.Dockerfile
    volumes:
      - ../configs/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-www.conf:ro
      - ../configs/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ../configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ${PROJECT_PATH}:/code
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - ${MYSQL_PORT}:3306

  site:
    image: nginx
    volumes:
      - ../configs/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PROJECT_PATH}:/code
  admin:
    image: adminer
  web:
    image: nginx
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ../configs/nginx/web.conf:/etc/nginx/conf.d/default.conf:ro
